spring:
  redis:
    database: 0
    # 连接远程server需要设置 bind 0.0.0.0以支持远程连接
    # 默认是bind 127.0.0.1 只能通过本地连接
    host: 192.168.1.140
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 10
        min-idle: 2